const mongoose = require('mongoose');

const { Schema } = mongoose.Schema;

// We will use _id auto generated by MongoDB as the primary key
const tradeSchema = new Schema({
  tradeType: {
    type: String,
    required: true,
  },
  symbol: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  },
  shares: {
    type: Number,
    required: true,
  },
  executionDate: {
    type: Date,
    required: true,
  },
  tradeBroker: String,
  tradeCommission: {
    type: Number,
    required: true,
  },
  updated: Date,
});

const Trade = mongoose.model('Trade', tradeSchema);

module.exports = Trade;
